# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.4
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: false
classname: Hexstruction
default_branch: main
description: Structure manipulation with Hex Casting
display_name: HexStruction
github_repo: hexstructiondummy
github_user: PetersonE1
homepage_url: https://petersone1.github.io/hexstruction
java_package: org.agent.hexstruction
kotlin_package: org.agent.hexstruction
mappings_name: Mojmap
minecraft_version_in_mod_version: true
mod_version: 1.1.0
modid: hexstruction
sources_url: https://github.com/PetersonE1/hexstruction
